# Generated by Django 3.2.4 on 2021-07-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_de_folga', models.DateField()),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
            ],
            options={
                'verbose_name': 'Folga',
                'verbose_name_plural': 'Folgas',
            },
        ),
    ]
