# Generated by Django 3.2.4 on 2021-07-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folga', '0004_alter_folga_dia_de_folga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folga',
            options={'verbose_name': 'Folga', 'verbose_name_plural': 'Folga'},
        ),
    ]
