# Generated by Django 3.2.4 on 2021-07-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0005_auto_20210713_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(help_text='Ex: 01/01/2021'),
        ),
    ]
