# Generated by Django 3.2.4 on 2021-07-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Médico')),
                ('sobrenome', models.CharField(max_length=20, verbose_name='Sobrenome')),
                ('data_de_admissao', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('posto_de_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posto.posto')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['nome'],
            },
        ),
    ]
