# Generated by Django 3.2.4 on 2021-07-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='data_de_admissao',
            field=models.DateField(auto_now=True),
        ),
    ]
